### ISSUE TITLE
Could bustools inspect support the same barcode file formats as bustools correct?

### ISSUE THREAD

**Issue by detrout** [BUStools/bustools#101]
In the barcode parsing code in bustools correct
https://github.com/BUStools/bustools/blob/master/src/bustools_correct.cpp#L711
it supports barcode files of the format 

```
AAAA GGGG TTTT
- TTTT CCCC
```

While the barcode reader in https://github.com/BUStools/bustools/blob/master/src/bustools_inspect.cpp#L59 requires the cartesian product style file
```
AAAATTTT
GGGGTTTT
TTTTTTTT
AAAACCCC
GGGGCCCC
TTTTCCCC
```

Because of this if you bustools inspect with the multiple list format barcode list these inspect attributes will be 0.
```
  "numBarcodesOnOnlist": 0,
  "percentageBarcodesOnOnlist": 0.000000,
  "numReadsOnOnlist": 0,
  "percentageReadsOnOnlist": 0.000000
```

**Comment by Yenaled** [comment]
Thanks Diane! :) I’ll keep note of this and fix it when I upgrade bustools!

**Comment by Yenaled** [comment]
Addressed in latest commit in devel branch
