### ISSUE TITLE
Basepairs in 34 b.p. cell barcode are being re-ordered

### ISSUE THREAD

**Issue by connersk** [BUStools/bustools#106]
Hi, I'm using `kallisto` and `bus tools` to process split pool scRNA-seq data that has a 34 base pair long cell barcode and a 10 base pair UMI.

In the final output, the cell barcode base pairs are returned in the wrong order. I.e. instead of returning the cell barcode `cbc` the software is returning `cbc[2:34] + cbc[23:34]` (with 0-indexing). I've confirmed this by manually inspecting the first 34 base pairs of the cell barcodes in my R1 fastq files.

Example code that generates these outputs is as follows. Note I do not run `bustools correct` because the cell barcodes in my R1 fastqs are already corrected by an upstream step in my pipeline.
```
kallisto bus         -i /path/to/kb.idx        -x 0,0,34:0,34,44:1,0,0    -t 60      -o output_dir /path/to/R1.fastq.gz  /path/to/R2.fastq.gz
bustools sort         -t 60         -o output_dir output.bus.sorted        output.bus
mkdir -p output_dir/genecounts
bustools count         -o output_dir/genecounts/         --genecounts         -g /path/to/t2g_gene_names.txt         -e output_dir/matrix.ec         -t /path/to/transcripts.txt         output_dir/output.bus.sorted
```

**Comment by Yenaled** [comment]
Barcodes >= 32 bp are not supported by bustools.

**Comment by connersk** [comment]
Thanks for the clarification, I'll try another approach.
