### ISSUE TITLE
Barcodes containing N

### ISSUE THREAD

**Issue by lonsbio** [BUStools/bustools#12]
Hi, 

Sequences containing N nucleotides seem to be replaced with a pseudorandom nucleotide as far as I can tell. In barcodes in particular I think this occurs before `bustools correct` and leads to some N containing barcodes being whitelisted, and others corrected. Not sure if this should be after, and let hamming distance decide?

Additionally, the pseudorandomness also seems a bit off, as in tests with a leading N in sequences, they  to be replaced with G every time. Perhaps the random seed is reset?

Attached test sequences to verify, three sequences  of which two lead with N in the R1 barcode:

`kallisto bus -i Homo_sapiens.GRCh38.cdna.all.idx -o bus_output_testseqs  <( gzip -c testseqs_r1.fa ) <( gzip -c testseqs_r2.fa) -x 10xv2
`

Before correction, they are already replaced: `bustools text bus_output_testseqs/output.bus -p`

```
CAACTAGTCTGCTGCT        ACGTGGGTCT      332519  1
GAACTAGTCTGCTGCT        ACGTGGGTCT      332519  1
GGGCACTGTCGATTGT        ACGTGGGTCT      332519  1
Read in 3 number of busrecords

```
and 

`bustools correct bus_output_testseqs/output.bus  -w 10xv2_whitelist.txt  -o bus_output_testseqs/output_correct.bus`

gives two in whitelist, rather than the one expected:

```
Found 737280 barcodes in the whitelist
Number of hamming dist 1 barcodes = 20550336
Processed 3 bus records
In whitelist = 2
Corrected = 0
Uncorrected = 1
```

I think the event is relatively rare, but clarity on the best approach would be valuable

[testseqs_r2.fa.txt](https://github.com/BUStools/bustools/files/3420017/testseqs_r2.fa.txt)
[testseqs_r1.fa.txt](https://github.com/BUStools/bustools/files/3420018/testseqs_r1.fa.txt)

Thanks

Andrew

**Comment by lakigigar** [comment]
Thanks. You make an interesting point. Indeed, kallisto converts Ns to (pseudorandom) nucleotides and this happens prior to writing of BUS format. This order allows for 2-bit encoding of nucleotides and is therefore convenient and efficient. You're right that if considering an N truly unknown one could ignore it in correction thereby saving some barcodes (although it could also possibly lead to erroneous assignment). I suspect, as you noted, that the number of barcodes where this makes a difference one way or another is negligible. Having said that, it may be useful to implement an option that records in a flag where in each barcode Ns have been observed. This is doable within the BUS format and could be useful for some applications.
