### ISSUE TITLE
problem with bustools capture

### ISSUE THREAD

**Issue by raymondlouie** [BUStools/bustools#13]
In the tutorial 

https://www.kallistobus.tools/velocity_tutorial.html

it says to run 

bustools capture -o introns_capture/ -c ../introns_transcripts.to_capture.txt -e matrix.ec -t transcripts.txt output.correct.sort.bus

However, I get the error message:

Error: capture list type must be specified (one of -s, -u, or -b)

If I then run with the -s command:

bustools capture -s -o introns_capture/ -c ../introns_transcripts.to_capture.txt -e matrix.ec -t transcripts.txt output.correct.sort.bus

there is nothing outputted in the introns_capture folder?

A related question: when I type "bustools capture", it says the output should be a file, not a directory:

Usage: bustools capture [options] bus-files

Options: 
-o, --output          File for captured output 

but the help-page

https://github.com/BUStools/bustools

says the output should be a directory:

Usage: bustools capture [options] bus-files

Options: 
-o, --output          Directory for output 

Thanks.

**Comment by sbooeshaghi** [comment]
The recent merge of the pull request to master means that those cloning the repo and compiling from source have a different version of capture than in the binary.

We will update the tutorial accordingly. In the meantime, the tutorial will work with the bustools binary v0.39.2 available here https://bustools.github.io/download

**Comment by raymondlouie** [comment]
Great thanks, it's working now.
