### ISSUE TITLE
Consider output in loom file format

### ISSUE THREAD

**Issue by slinnarsson** [BUStools/bustools#14]
Hi! Thanks for the great work on kallisto and bustools - it's impressively fast and looks accurate so far. 

Since kallisto already uses HDF5, would you consider an option to write the output of kallisto+bustools to a loom file (which is based on HDF5)? Loom files are especially convenient for RNA velocity, since they support multiple layers. See http://loompy.org for docs and spec.  

Ideally, bustools would write the count output to a new loom file (matrix plus row and column metadata), or add a layer to an existing loom file (e.g. for adding unspliced counts to a file with spliced counts, or for feature barcodes, or both at the same time).

The loom spec is simple enough that you can write the file directly using the HDF5 API in C/C++. I'll be happy to help if anything is unclear in the spec.

**Comment by lakigigar** [comment]
Thanks for the suggestion. We’ll definitely look into this. A bus2loom tool is a good idea.

**Comment by lakigigar** [comment]
The [kb wrapper](https://pypi.org/project/kb-python/) now supports loom output.
