### ISSUE TITLE
Missing -s flag for bedtools getfasta

### ISSUE THREAD

**Issue by slinnarsson** [BUStools/bustools#16]
In the RNA Velocity tutorial (section on how to build a cDNA and intron index), I think an `-s` flag is missing in this command:

```
bedtools getfasta -name -fo introns.fa -fi species.primary_assmebly.fa -bed introns.bed
```

Without it, I suppose half the introns will be on the wrong strand?

**Comment by lakigigar** [comment]
`[kb ref](https://pypi.org/project/kb-python/)` solves this.
