### ISSUE TITLE
conda install bustools downgrades kallisto?

### ISSUE THREAD

**Issue by jamestwebber** [BUStools/bustools#21]
It looks like the recipes have slightly different requirements for the `hdf5` library, so when I do this:

`conda install kallisto`
and then
`conda install bustools`

The first command installs kallisto 0.46 and then the second one wants to downgrade kallisto to 0.43.

**Comment by jamestwebber** [comment]
Ah my colleague just did this in a new environment and it didn't happen to him, so it seems like this was an issue with trying to upgrade my existing kallisto/bustools installation.

**Comment by jamestwebber** [comment]
Well, it is still happening when I make a fresh environment, but we seem to be in some crazy dependency hell where our conda environments don't even agree on which version of Python is most recent...so it's probably not _your_ fault.

It appears that conda will install bustools 0.39.2 for python 3.7.4 and 0.39.3 for python 3.7.3 (which downgrades kallisto)

**Comment by apeltzer** [comment]
So this is a typical conda "issue" as you might have figured out yourself by now: Bioconda packages are built against a specific Python version at some point, so if you want to have the newest kallisto version to be installed alongside 0.39.3, you'd need to rebuild for Python3.X by bumping [the recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kallisto/meta.yaml). 

It's a bit more complicated: It's not just the Python Version affecting the build but also `cmake` and thus the c-compiler used by bioconda. 

That way, you'd get the newest `kallisto` to be built with the same Python3.X version AND you can install it alongside the `bustools` recipe hopefully too.

**Comment by apeltzer** [comment]
The latest `kallisto=0.46.0-1` package installs well with `bustools 0.39.3-0` - can be closed I think 👍

**Comment by jamestwebber** [comment]
I just tried to install both from a fresh environment and it gives me `kallisto-0.46.0` and `bustools-0.39.2`. Happened on both an Ubuntu box and on OS X. ¯\\\_(ツ)_/¯ 

Building `bustools` from src was painless, though, thanks to the documentation. So that's a reasonable solution for now. Feel free to close this issue, as I think it's just a matter of bioconda catching up to your progress.

**Comment by lakigigar** [comment]
Seems it's now up to date.
