### ISSUE TITLE
Please add some checks to your c functions!

### ISSUE THREAD

**Issue by stela2502** [BUStools/bustools#25]
Hi!
I just wasted a whole day trying to understand why I do not get a data matrix out of your pipeline:
bustools correct -w ../10xv2_whitelist.txt -p output.bus | bustools sort -T tmp/ -t 4 -p - | bustools count -o genecount/genes -g ../transcripts_to_genes.txt -e matrix.ec -t transcripts.txt --genecounts -
At the end of the day I had forgotten to create the tmp path. And the bustools sort program did not even crash or report any error. It just created an empty bus file.

Coud you please fix that by adding a check if the tmp path exists?

Otherwise a really cool tool - thank you!

**Comment by pmelsted** [comment]
Thanks for reporting this. Looking at https://github.com/BUStools/bustools/blob/master/src/bustools_main.cpp#L538 I see that I only check if it is a directory that exists and otherwise assume it's a file prefix. I'll add checks for this in the next release.

**Comment by stela2502** [comment]
Thank you!

**Comment by stela2502** [comment]
A similar strange behavior can be seen in the usage of the 'bustools count -o genecount/genes' option. As all out-files in folder genecount get a prefix 'genes' I assume that the sub-folder that is also created (genecount/genes) is actually useless. Am I right?
http://www.cplusplus.com/forum/windows/85516/

**Comment by pmelsted** [comment]
This has been fixed in the latest issue.
