### ISSUE TITLE
UMI counts by transcripts 

### ISSUE THREAD

**Issue by yarloz-old** [BUStools/bustools#26]
Dear developers,   

Do you consider an additional option to calculate expression by transcripts but no by genes only? That would be useful in some variants of analysis. Is there an easy way I can calculate umi counts by transcripts now?

Best regards,
Yaroslav Lozinsky

**Comment by pmelsted** [comment]
The `bustools count` has an option of working with TCCs using the `-m` flag. This can then be analyzed using the methods from https://www.nature.com/articles/s41592-018-0303-9
