### ISSUE TITLE
t2g.py does not create proper transcript_to_gene.txt

### ISSUE THREAD

**Issue by alexblaessle** [BUStools/bustools#27]
Dear bustools team,

I just had a slightly tough time wrangling with your getting started example (especially the "explained" one).  I followed the "explained" tutorial, but ended up with an empty gene count matrix (no genes). After an hour of debugging, I think I found the error.

When I follow the "explained" getting started tutorial, I download the ``t2g.py`` and run 

```
./t2g.py < Mus_musculus.GRCm38.96.gtf > transcripts_to_genes.txt
```

And get a file that looks like 

```
ENSMUST00000193812	ENSMUSG00000102693	4933401J01Rik
ENSMUST00000082908	ENSMUSG00000064842	Gm26206
ENSMUST00000162897	ENSMUSG00000051951	Xkr4
ENSMUST00000159265	ENSMUSG00000051951	Xkr4
ENSMUST00000070533	ENSMUSG00000051951	Xkr4
ENSMUST00000192857	ENSMUSG00000102851	Gm18956
ENSMUST00000195335	ENSMUSG00000103377	Gm37180
ENSMUST00000192336	ENSMUSG00000104017	Gm37363
ENSMUST00000194099	ENSMUSG00000103025	Gm37686
ENSMUST00000161581	ENSMUSG00000089699	Gm1992
```
However, looking at transcripts.txt in ``bus_output`` later I have

```
ENSMUST00000178537.1
ENSMUST00000178862.1
ENSMUST00000177564.1
ENSMUST00000196221.1
ENSMUST00000179664.1
ENSMUST00000179520.1
ENSMUST00000179883.1
ENSMUST00000195858.1
ENSMUST00000179932.1
ENSMUST00000180001.1
```

So it seems that the notation of the transcripts is not identical and this seems to be the reason why I don't see any genes. Interestingly, the ``transcript_to_gene.txt`` that you provide to download looks like 

```
ENSMUST00000119854.7	ENSMUSG00000037736.18	Limch1
ENSMUST00000204196.1	ENSMUSG00000029804.17	Herc3
ENSMUST00000070080.5	ENSMUSG00000056124.5	B4galt6
ENSMUST00000147408.2	ENSMUSG00000052516.19	Robo2
ENSMUST00000033908.13	ENSMUSG00000031511.15	Arhgef7
ENSMUST00000223903.1	ENSMUSG00000037126.16	Psd
ENSMUST00000235946.1	ENSMUSG00000118049.1	AC166172.3
ENSMUST00000082868.1	ENSMUSG00000064802.1	Gm24036
ENSMUST00000187399.1	ENSMUSG00000090925.2	1810064F22Rik
ENSMUST00000194793.1	ENSMUSG00000103497.1	Gm37407
```

with the correct transcript names.  

Is there an option or way to fix this?

**Comment by lakigigar** [comment]
We have wrapped this into the `[kb ref](https://pypi.org/project/kb-python/)` command.
