### ISSUE TITLE
barcodes is empty

### ISSUE THREAD

**Issue by kaji331** [BUStools/bustools#28]
I use the newest release of bustools/kallisto and following the steps of https://www.kallistobus.tools/getting_started. I can complete kallisto bus and bustools correct/sort/count in pipe mode. However, I get an empty genes.barcodes.txt in the genecount folder. I try ensembl and ucsc version of mouse transcript.

**Comment by kaji331** [comment]
I can get a good result using the first release of BUStools in github.com

**Comment by ruqianl** [comment]
I got the same results. Empty gene.barcodes.txt with the newest version 0.39.3.

Solved by creating the tmp folder. see #25

**Comment by pmelsted** [comment]
@kaji331 can you check that you have all the folders. Are there any error messages reported, it helps to separate the bustools commands rather than piping when you have an error
e.g.
```
bustools correct -w ../10xv2_whitelist.txt -o output.corrected.bus output.bus 
```
then `output.corrected.bus` becomes the input for the next command

**Comment by kaji331** [comment]
> @kaji331 can you check that you have all the folders. Are there any error messages reported, it helps to separate the bustools commands rather than piping when you have an error
> e.g.
> 
> ```
> bustools correct -w ../10xv2_whitelist.txt -o output.corrected.bus output.bus 
> ```
> 
> then `output.corrected.bus` becomes the input for the next command

OK. I try separated commands and pipe commands again. There're no error messages reported. I make genecount folder, no tmp folder. That's the reason for the problem. I think we'd better add an error message for folder checking. If bustools can check and create folders automatically, it would be wonderful.

**Comment by kaji331** [comment]
> I got the same results. Empty gene.barcodes.txt with the newest version 0.39.3.
> 
> Solved by creating the tmp folder. see #25

Thank you very much!
