### ISSUE TITLE
Interface for python/R import?

### ISSUE THREAD

**Issue by chriscainx** [BUStools/bustools#3]
Hi,
Can you provide a direct wrapper for R/python? I'm thinking if it's c, a reader function wouldn't be hard to implement (pybind11/Rcpp). The current solution (text) isn't elegant since it's binary -> text -> binary. 
Thanks!! luv kallisto/bus.

**Comment by sbooeshaghi** [comment]
Hey! If you haven't already, check out our preprint on using bustools https://www.biorxiv.org/content/10.1101/673285v1, and our tutorials on https://www.kallistobus.tools/.

We have released binaries for bustools that allow you to go form BUS file to count matrices without having to import anything into python or R. If you are interested in manipulating BUS files in R, please check out https://github.com/BUStools/BUSpaRse
