### ISSUE TITLE
Empty folder generated with counts

### ISSUE THREAD

**Issue by astrovsky01** [BUStools/bustools#30]
When running ```bustools count```, the -o flag names the files correctly, but every time I run it, it creates an extra empty folder named as the pure input of the flag. Should that be populated, or is it an error? I don't see it in the tutorial video either (https://www.youtube.com/watch?v=hWxnL86sak8).

Thanks!

bustools count -o folder/example ... --genecounts output.bus

Generated file structure
```
|folder
|--example.barcodes.txt
|--example.genes.txt
|--example.mtx
|--example
    |--
```

**Comment by pmelsted** [comment]
Thanks for reporting this, we will fix this in the next release.
