### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by astrovsky01** [BUStools/bustools#31]
When running certain functions with bustools, I repeatedly get segmentation fault 11. One example is inspect, which fails with one file, but passes with another. I should clarify that the file inspect failed with works with every other function. 
I have also gotten the seg fault for counts and project.

**Comment by pmelsted** [comment]
If you run into segfaults we would appreciate getting more information, especially if it can be reproduced using public data. Please report the command used and the command line paramers, along with the datasets used if publicly available.

**Comment by astrovsky01** [comment]
ping @pmelsted
The files are here: https://github.com/galaxyproject/tools-iuc/pull/2473/files?file-filters%5B%5D=.bus&file-filters%5B%5D=.ec&file-filters%5B%5D=.txt

Failed commands:
    * On mac:
        * bustools inspect -o inspect.json -e matrix.ec -w whitelist.txt testbus.bus
    * In a linux environment:
        *  bustools count -g txg.txt -e matrix.ec -t transcripts.txt testbus.bus
        *  bustools project -g txg.txt -e matrix.ec -t transcripts.txt testbus.bus
