### ISSUE TITLE
Mix-up spliced/unspliced in velocity tutorials

### ISSUE THREAD

**Issue by julien-roux** [BUStools/bustools#33]
Is this the right place to report mistakes in tutorials? Otherwise, please let me know where to report.

I think there is a mix up in the `bustools count` calls in the velocity tutorials (here: https://www.kallistobus.tools/velocity_tutorial.html and here: https://github.com/BUStools/getting_started/blob/master/kallisto_bus_mouse_nuclei_tutorial.ipynb, I might have missed other occurrences).

 The `bustools count` command is called in the spliced counts and saved in the `unspliced/` directory, and vice-versa. Here are the problematic commands from the first tutorial:

```
$ bustools capture -o cDNA_capture/ -c ../cDNA_transcripts.to_capture.txt -e matrix.ec -t transcripts.txt output.correct.sort.bus
$ bustools capture -o introns_capture/ -c ../introns_transcripts.to_capture.txt -e matrix.ec -t transcripts.txt output.correct.sort.bus
$ bustools count -o unspliced/u -g ../cDNA_introns.t2g.txt -e cDNA_capture/split.ec -t transcripts.txt --genecounts cDNA_capture/split.bus
## Shouldn't the above be saved in spliced/u?
$ bustools count -o spliced/s -g ../cDNA_introns.t2g.txt -e introns_capture/split.ec -t transcripts.txt --genecounts introns_capture/split.bus
## Shouldn't the above be saved in unspliced/u?
```

The RNA velocity tutorial using R (https://bustools.github.io/BUS_notebooks_R/velocity.html) uses a different approach (captures reads in the complement of intronic or exonic regions) but seems correct.

**Comment by julien-roux** [comment]
Or is this just a change in behavior of `bustools capture` between versions `0.39.2` and `0.39.3`?

**Comment by lambdamoses** [comment]
Yes, the R tutorial has been updated for `0.39.3`, but the command line tutorial has not been updated.
