### ISSUE TITLE
Resizing glist when running bustools count

### ISSUE THREAD

**Issue by gtca** [BUStools/bustools#38]
https://github.com/BUStools/bustools/blob/f0350e7ac61489485b60d53b6961a25596c333fa/src/Common.cpp#L204-L206

Hey, thanks a lot for a great tool!

I've been experiencing some problems running `bustools count`: for some of our data, it results in almost empty gene (or transcript) count matrices. 
So I've stumbled upon this part of the code while debugging the transcript quantification part of our pipeline.

Aren't we supposed to grow the vector (i.e. `if (k >= n)`) at this part of the code? It seems that it rather shrinks the vector, which might explain the problems I've encountered.
I have checked that this change would give a slightly different, though quite a similar, `gene.mtx` file for the [getting started tutorial](https://www.kallistobus.tools/getting_started) compared to the current master (or devel) branch.
Would be happy to hear your comments!

**Comment by pmelsted** [comment]
The code is correct (basically all the things that belong to the intersection have been moved up front). If you are running into problems you can use the mailing list for help.
