### ISSUE TITLE
Segmentation fault when using bustools sort

### ISSUE THREAD

**Issue by tracytktran** [BUStools/bustools#39]
Hi,
I got the following error when I tried to sort the output bus file. I'm using the latest version of kallisto and bustools. and output.correct.bus is 2,017,841 KB in size so I guess it should have content to be sorted. Wondering if you have any advice here?
Thank you!

$ bustools sort -t 4 -o output.correct.sort.bus output.correct.bus
Read in 0 BUS records
Segmentation fault

**Comment by pmelsted** [comment]
Are you running this on windows?

Can you try adding the option `-m 100000000` to sort?
