### ISSUE TITLE
TCC mtx file is not valid

### ISSUE THREAD

**Issue by lambdamoses** [BUStools/bustools#40]
It seems that the mtx file for TCC matrices generated by `bustools` is not valid. When I tried to read the file into R with `Matrix::readMM`, I got this error:

```
Error: readMM(): column values 'j' are not in 1:nc
```

The column index must be wrong for some entries. For instance, for one of the files I inspected, the maximum column index is actually 738421, while the `mtx` file indicates 499458. Meanwhile, for that dataset, the `matrix.ec` file has 489048 lines.

**Comment by pmelsted** [comment]
Can you send me a the path to where the data is, both the fastq and bus files

**Comment by vivekbhr** [comment]
I am facing this issue with my data too (v0.39.4).. what was the solution?

**Comment by lambdamoses** [comment]
Pall said this problem is fixed in the development version.

**Comment by vivekbhr** [comment]
Thanks @lambdamoses . I'll try re-compiling from the devel branch

**Comment by vivekbhr** [comment]
devel branch seems to indeed fix the issue :+1:
