### ISSUE TITLE
gene.gene.txt no symbols 

### ISSUE THREAD

**Issue by BarryDigby** [BUStools/bustools#48]
I have followed the ["getting started"](https://www.kallistobus.tools/getting_started) tutorial and generated the ```barcodes```, ```genes``` and ```mtx``` files. The ```gene.genes.txt``` file does not have the corresponding gene symbols. 

I read [elsewhere](https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.html#finding-marker-genes) that cellranger outputs a genes file with 2 columns, ID + Symbol

I have tested a different dataset from 10X genomics and get the same result.. is this expected behaviour? 

This is being addressed on [biostars](https://www.biostars.org/p/418229/#418309)

I am sorry, I did not realise your team monitored posts there. Can you delete this message please?

**Comment by soohyuna** [comment]
I ran into the same problem!! Has this issue been solved?

**Comment by BarryDigby** [comment]
@soohyuna I wrote about how to fix this using python scripts developed by the Kallisto team. 

https://github.com/BarryDigby/scRNA-Seq/blob/master/an_unbridled_rage.md

p.s You might want to use `kb_python` wrapper tool instead of `kallisto bustools`. At the time I came across this error, the Kallisto team were rolling out `kb_python` so I didn't know any better!

**Comment by soohyuna** [comment]
@BarryDigby  Thank you for the link!

**Comment by sbooeshaghi** [comment]
@BarryDigby thanks for the tutorial showing how to augment gene ids with their names.
