### ISSUE TITLE
Conda Recipe

### ISSUE THREAD

**Issue by apeltzer** [BUStools/bustools#5]
Just as a side-note for your team, there is a bustools recipe for bioconda now available (for 0.39.2 release): 

https://anaconda.org/bioconda/bustools (badges are here: https://anaconda.org/bioconda/bustools/badges ) 

Which could e.g. be added to the README for users having issues with cmake and/or installation. As there is `kallisto` in bioconda too, its really easy to install both alongside even in the same conda environment:

**Comment by pmelsted** [comment]
Thanks, we'll add this to the manual and documentation

**Comment by lakigigar** [comment]
We've added instructions on the bustools website. Thanks!

**Comment by apeltzer** [comment]
Thank you for making this tool!
