### ISSUE TITLE
Counts matrix without considering UMI

### ISSUE THREAD

**Issue by caleblareau** [BUStools/bustools#63]
Is this possible? I have a setting where I don't have a UMI _per se_ but I want to utilize the kallisto | bustools pipeline to quantify a set of kmers over a large number of cell barcodes. I can imagine a work around by exporting the bus to a text file if this isn't supported natively...

**Comment by dawe** [comment]
I had the same issue when using kallisto+bustools for scATAC data. I believe it is possible, in the meantime a handy workaround is to generate random UMI (e.g. in a separate fastq file with identical read names)

**Comment by sbooeshaghi** [comment]
If you just want to just count the number of reads per cell  barcode per gene then install bustools from the covid branch (https://github.com/BUStools/bustools/tree/covid)  sort `output.bus`, correct the barcodes, sort it again, then run `bustools count --cm` to generate a count matrix that uses the multiplicities column.

**Comment by caleblareau** [comment]
sounds great-- will give it a go. Thanks @sbooeshaghi
