### ISSUE TITLE
Mus musculus index files for RNA velocity

### ISSUE THREAD

**Issue by ykykyksa** [BUStools/bustools#7]
Hi,

I would like to try RNA velocity with following your tutorial with our actual datasets derived from Drop-seq with mouse cells, but tutorial gives the files required for analyzing human cells. It would be great if you could share index files including cDNA and introns, probably used for producing figure 3 of bioRxiv paper "Modular and efficient pre-processing of single-cell RNA-seq".

Thank you for providing us opportunities to get more information from scRNA-seq data and interpret Biology there.

**Comment by sbooeshaghi** [comment]
The mouse RNA velocity files are below. Note that this index requires that the biological read length is of length 98bp:

https://github.com/pachterlab/MBGBLHGP_2019/releases/tag/figure_3_files
