### ISSUE TITLE
bustools sort/count fails silently when outputting to nonexistent directory

### ISSUE THREAD

**Issue by dibidave** [BUStools/bustools#8]
Specifically, in the tutorial from https://www.kallistobus.tools/getting_started.html, in these lines:
```
$ cd bus_output/
$ mkdir genecount/ tmp/
$ bustools correct -w ../10xv2_whitelist.txt -p output.bus | bustools sort -T tmp/ -t 4 -p - | bustools count -o genecount/genes -g ../transcripts_to_genes.txt -e matrix.ec -t transcripts.txt --genecounts -
```
If you omit the ```mkdir``` command, the process runs but doesn't output anything, and doesn't alert the user that it couldn't output to the requested directory.

**Comment by pmelsted** [comment]
Thanks for reporting this, we will fix this bug in the next release.
