### ISSUE TITLE
Converting .txt back to BUS?

### ISSUE THREAD

**Issue by jhkliu42** [BUStools/bustools#86]
Hi,

I would like to work with bustools text to convert a BUS file to .txt, perform some manipulations, and then convert the new .txt back to BUS. Is there code that can do this? Specifically, what I want to do is take a converted .txt file, subsample the reads to a smaller fraction, and then convert it back to BUS so I can then run bus count. Ideally I want to avoid writing things from scratch if there is already functionality.

**Comment by Yenaled** [comment]
Yes, use the "bustools fromtext" command (enter it without any options to view the help page on how to use it).

**Comment by pmelsted** [comment]
If you want to subsample reads there is an option to do this in `bustools count` called `--downsample` 

This downsamples reads, not just BUS records, so if you sample at a rate of 0.5 and  the same record is observed in 2 reads it has a .75 probability of showing up in the output.
