### ISSUE TITLE
Bustools correct - Weird echo

### ISSUE THREAD

**Issue by victorcat4** [BUStools/bustools#87]
Hi I ran,

Bustools correct -w 10xv3_whitelist.txt -o sorted_output.bus -p output.bus after kallisto bus. Here is what printed on my screen while the cmd is running: 

<img width="643" alt="Screenshot 2023-02-04 at 10 13 42 AM" src="https://user-images.githubusercontent.com/95758194/216778755-f4d74dd6-787e-49de-90a3-2f5307000235.png">

Is this normal ?

**Comment by Yenaled** [comment]
No, that should not happen unless the contents of the BUS file (a binary) was accidentally printed. (Perhaps because you supplied the -p option?)

**Comment by victorcat4** [comment]
Thanks that was indeed the reason. I didn't saw it but the manual say :
"Note that in many cases using -p will write a binary file to stdout which may garble your terminal unless parsed by a subsequent bustools command."
