### ISSUE TITLE
Filter BUS file

### ISSUE THREAD

**Issue by ollieeknight** [BUStools/bustools#93]
Heya,

Essentially what I want to do is figure out the sequencing saturation per transcript. This is particularly useful for ADT libraries where there are few markers, and I can then distinguish from hashtags.

I would like to first try and filter a BUS file for the list of barcodes outputted by cellranger atac, but I'm having troubles doing this. Does anyone have any advice/guidance?

Thanks so much,

Ollie

**Comment by Yenaled** [comment]
To filter a BUS file for a list of barcodes outputted by cellranger, put the cellranger barcodes in a text file, and supply that to the bustools capture command with the --barcode option.

**Comment by ollieeknight** [comment]
thank you!!
