### ISSUE TITLE
Question on Multi-part barcode correction in bustools 0.43.0

### ISSUE THREAD

**Issue by JohnMMa** [BUStools/bustools#96]
This is a relatively simple question. The release notes for v0.43.0 states, 
> - The onlist supplied to bustools correct can have multiple columns so that each component of the barcode is correct[ed] independently.

Given `bustools correct` corrects unitary barcodes (such as those from 10X) that are 1 Hamming distance from the whitelist, does that mean if a multi-part whitelist is provided (which is likely the case when using combinatorial indexing, such as Parse or Scale), _each_ component is corrected to a maximum of 1 Hamming distance--e.g. for a 4-component barcode, there's a likelihood that a barcode can be corrected to up to 4 Hamming distances?

**Comment by Yenaled** [comment]
Yes, that is exactly correct.

**Comment by JohnMMa** [comment]
Thanks @Yenaled ! I will close this issue.
